/** Port of kinoko's EventState. */
export enum EventState {
  // ContiMove
  CONTIMOVE_BOARDING = 'CONTIMOVE_BOARDING',
  CONTIMOVE_WAITING = 'CONTIMOVE_WAITING',
  CONTIMOVE_INSIDE = 'CONTIMOVE_INSIDE',
  CONTIMOVE_MOBGEN = 'CONTIMOVE_MOBGEN',
  // Elevator
  ELEVATOR_GOING_DOWN = 'ELEVATOR_GOING_DOWN',
  ELEVATOR_2ND_FLOOR = 'ELEVATOR_2ND_FLOOR',
  ELEVATOR_GOING_UP = 'ELEVATOR_GOING_UP',
  ELEVATOR_99TH_FLOOR = 'ELEVATOR_99TH_FLOOR',
  // Subway
  SUBWAY_BOARDING = 'SUBWAY_BOARDING',
  SUBWAY_WAITING = 'SUBWAY_WAITING',
  SUBWAY_INSIDE = 'SUBWAY_INSIDE',
  // Airport
  AIRPORT_BOARDING = 'AIRPORT_BOARDING',
  AIRPORT_WAITING = 'AIRPORT_WAITING',
  AIRPORT_INSIDE = 'AIRPORT_INSIDE',
}
