import { registerJobHandler } from './JobManager';
import { Beginner } from './Beginner';
import { Hero } from './Warrior/Hero';
import { Fighter } from './Warrior/Fighter';
import { Crusader } from './Warrior/Crusader';
import { Page } from './Warrior/Page';
import { WhiteKnight } from './Warrior/WhiteKnight';
import { Paladin } from './Warrior/Paladin';
import { Spearman } from './Warrior/Spearman';
import { DragonKnight } from './Warrior/DragonKnight';
import { DarkKnight } from './Warrior/DarkKnight';
import { FPWizard } from './Magician/FPWizard';
import { FPMage } from './Magician/FPMage';
import { FPArchMage } from './Magician/FPArchMage';
import { ILWizard } from './Magician/ILWizard';
import { ILMage } from './Magician/ILMage';
import { ILArchMage } from './Magician/ILArchMage';
import { Cleric } from './Magician/Cleric';
import { Priest } from './Magician/Priest';
import { Bishop } from './Magician/Bishop';
import { Hunter } from './Archer/Hunter';
import { Ranger } from './Archer/Ranger';
import { BowMaster } from './Archer/BowMaster';
import { Crossbowman } from './Archer/Crossbowman';
import { Sniper } from './Archer/Sniper';
import { Marksman } from './Archer/Marksman';
import { Assassin } from './Thief/Assassin';
import { Hermit } from './Thief/Hermit';
import { NightLord } from './Thief/NightLord';
import { Bandit } from './Thief/Bandit';
import { ChiefBandit } from './Thief/ChiefBandit';
import { Shadower } from './Thief/Shadower';
import { BladeRecruit } from './Thief/BladeRecruit';
import { BladeAcolyte } from './Thief/BladeAcolyte';
import { BladeSpecialist } from './Thief/BladeSpecialist';
import { BladeLord } from './Thief/BladeLord';
import { BladeMaster } from './Thief/BladeMaster';
import { Brawler } from './Pirate/Brawler';
import { Marauder } from './Pirate/Marauder';
import { Buccaneer } from './Pirate/Buccaneer';
import { GunSlinger } from './Pirate/GunSlinger';
import { Outlaw } from './Pirate/Outlaw';
import { Corsair } from './Pirate/Corsair';
import { Noblesse } from './cygnus/Noblesse';
import { DawnWarrior } from './cygnus/DawnWarrior';
import { BlazeWizard } from './cygnus/BlazeWizard';
import { WindArcher } from './cygnus/WindArcher';
import { ThunderBreaker } from './cygnus/ThunderBreaker';
import { Legend } from './legends/Legend';
import { Aran } from './Aran';
import { Evan } from './Evan';
import { Citizen } from './resistance/Citizen';
import { BattleMage } from './BattleMage';
import { WildHunter } from './WildHunter';
import { Mechanic } from './Mechanic';
import { GM } from './gamemaster/GM';
import { SuperGM } from './gamemaster/SuperGM';

export function registerAllJobHandlers(): void {
  registerJobHandler(0, new Beginner());
  registerJobHandler(110, new Fighter());
  registerJobHandler(111, new Crusader());
  registerJobHandler(112, new Hero());
  registerJobHandler(120, new Page());
  registerJobHandler(121, new WhiteKnight());
  registerJobHandler(122, new Paladin());
  registerJobHandler(130, new Spearman());
  registerJobHandler(131, new DragonKnight());
  registerJobHandler(132, new DarkKnight());
  registerJobHandler(210, new FPWizard());
  registerJobHandler(211, new FPMage());
  registerJobHandler(212, new FPArchMage());
  registerJobHandler(220, new ILWizard());
  registerJobHandler(221, new ILMage());
  registerJobHandler(222, new ILArchMage());
  registerJobHandler(230, new Cleric());
  registerJobHandler(231, new Priest());
  registerJobHandler(232, new Bishop());
  registerJobHandler(310, new Hunter());
  registerJobHandler(311, new Ranger());
  registerJobHandler(312, new BowMaster());
  registerJobHandler(320, new Crossbowman());
  registerJobHandler(321, new Sniper());
  registerJobHandler(322, new Marksman());
  registerJobHandler(410, new Assassin());
  registerJobHandler(411, new Hermit());
  registerJobHandler(412, new NightLord());
  registerJobHandler(420, new Bandit());
  registerJobHandler(421, new ChiefBandit());
  registerJobHandler(422, new Shadower());
  registerJobHandler(430, new BladeRecruit());
  registerJobHandler(431, new BladeAcolyte());
  registerJobHandler(432, new BladeSpecialist());
  registerJobHandler(433, new BladeLord());
  registerJobHandler(434, new BladeMaster());
  registerJobHandler(510, new Brawler());
  registerJobHandler(511, new Marauder());
  registerJobHandler(512, new Buccaneer());
  registerJobHandler(520, new GunSlinger());
  registerJobHandler(521, new Outlaw());
  registerJobHandler(522, new Corsair());
  registerJobHandler(1000, new Noblesse());
  registerJobHandler(1100, new DawnWarrior());
  registerJobHandler(1200, new BlazeWizard());
  registerJobHandler(1300, new WindArcher());
  registerJobHandler(1500, new ThunderBreaker());
  registerJobHandler(2000, new Legend());
  registerJobHandler(2001, new Evan());
  registerJobHandler(2100, new Aran());
  registerJobHandler(3000, new Citizen());
  registerJobHandler(3200, new BattleMage());
  registerJobHandler(3300, new WildHunter());
  registerJobHandler(3500, new Mechanic());
  registerJobHandler(500, new GM());
  registerJobHandler(510, new SuperGM());
}
