export enum BroadcastMsgType {
  Notice             = 0,
  PopUpMessage       = 1,
  DarkBlueOnLightBlue = 2,
  Megaphone          = 3,
  SlideNotice        = 4,
  PartyChat          = 5,
  BlueChat_ItemInfo  = 6,
  GM_ErrorMessage    = 7,
  ItemMegaphone      = 8,
  ItemMegaphoneNoItem = 9,
  TripleMegaphone    = 10,
  YellowChatFiled_ItemInfo = 11,
  BlowWeather        = 12,
  TryRegisterAutoStartQuest = 13,
  TryRegisterAutoStartQuest_NoAnnouncement = 14,
  SwedishFlag        = 15,
  RedWithChannelInfo = 16,
  WhiteYellow_ItemInfo = 17,
  BlueChat_ItemInfo_2 = 18,
  WhiteYellow        = 19,
  PopUpNotice        = 20,
  Yellow             = 21,
  Yellow_2           = 22,
  MegaphoneNoMessage = 23,
  BalloonMessage     = 24,
}
