export enum ShopResultType {
  BuySuccess = 0,
  BuyNoStock = 1,
  BuyNoMoney = 2,
  BuyUnknown = 3,
  SellSuccess = 4,
  SellNoStock = 5,
  SellIncorrectRequest = 6,
  SellUnknown = 7,
  RechargeSuccess = 8,
  RechargeNoStock = 9,
  RechargeNoMoney = 10,
  RechargeIncorrectRequest = 11,
  RechargeUnknown = 12,
  BuyNoToken = 13,
  LimitLevelLess = 14,
  LimitLevelMore = 15,
  CantBuyAnymore = 16,
  TradeBlocked = 17,
  BuyLimit = 18,
  ServerMsg = 19,
}
